<!doctype html>
<?php
/**
 * 2017-05-07
 * @var string $headAdditional	An empty string for now.
 * @var string $headAttributes	An empty string for now.
 * @var string $headContent		<meta>, <title>, <link>, <script>.
 * @var string $htmlAttributes	«lang='en-US'».
 * @var string $layoutContent
 * @see \Magento\Framework\View\Result\Page::render()
 *		$output = $this->getLayout()->getOutput();
 *		$this->assign('layoutContent', $output);
 * https://github.com/magento/magento2/blob/2.1.6/lib/internal/Magento/Framework/View/Result/Page.php#L243-L244
 * @var string $requireJs
 */
?>
<html <?= $htmlAttributes ?>>
<head>
<?php /* 2017-05-07 M2 does not provide a way to set an exact static asset ordering, so I add the font manually. */ ?>
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' />
<?= df_cc_n($headAttributes, $requireJs, $headContent, $headAdditional) ?>
</head>
<body>
<?= $layoutContent ?>
<script>require([
	'Df_Core/thirdParty/HighlightJs/main'
	,'https://cdnjs.cloudflare.com/ajax/libs/anchor-js/3.2.2/anchor.js'
], function(hljs, anchorJS) {
	hljs.initHighlighting();
	// 2017-05-09
	// https://www.bryanbraun.com/anchorjs/#installation
	// https://www.bryanbraun.com/anchorjs/#dont-run-it-too-late
	// «right appends the anchor to the end of the element.
	// left places it to the left, in the margin.»
	// Default: right
	// https://www.bryanbraun.com/anchorjs/#options
	(new anchorJS({icon: '', placement: 'left'})).add('h2');
	(new anchorJS({icon: '', placement: 'left'})).add('h3')
});</script>
<?php if (!df_my_local()) { ?>
<!-- 2023-03-02 "Implement Google Analytics 4": https://github.com/mage2pro/portal/issues/3 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1FS3Y48ZT8"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', '<?= df_cfg('google/analytics/account') ?>');
</script>
<?php } ?>
</body>
</html>